version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static_backend/
      - media:/media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static_backend/
    volumes:
      - static:/static_backend
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static:/static_backend
      - media:/media/