version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data
  backend:
    image: 0702irisha/foodgram-project-react_backend
    env_file: .env
    volumes:
      - static:/static_backend/
      - media:/media/
    depends_on:
      - db
  frontend:
    image: 0702irisha/foodgram-project-react_frontend
    command: cp -r /app/build/. /static_backend/
    volumes:
      - static:/static_backend
  gateway:
    image: 0702irisha/foodgram-project-react_nginx
    ports:
      - 9090:80
    volumes:
      - static:/static_backend
      - media:/media/
    depends_on:
      - backend
      - frontend