version: '3.3'
services:
  db:
    image: postgres:13.0
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  backend:

    container_name: app
    image: 0702irisha/food_backend
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  frontend:

    container_name: front
    image: 0702irisha/food_front
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db

  nginx:

    image: 0702irisha/food_nginx
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:

  postgres_data:
  static_value:
  media_value:
