# Generated by Django 3.2 on 2023-10-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Добавьте фото готового блюда', upload_to='recipe_img/', verbose_name='Фото блюда'),
        ),
    ]
