# Generated by Django 3.2 on 2023-09-24 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsForRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Действия')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Дейстия',
            },
        ),
        migrations.RemoveField(
            model_name='shopping_list',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shopping_list',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscriptions',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Shopping_list',
        ),
        migrations.AddField(
            model_name='actionsforrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
