# Generated by Django 3.2 on 2023-09-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230924_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_list',
            fields=[
                ('actionsforrecipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.actionsforrecipe')),
            ],
            bases=('recipes.actionsforrecipe',),
        ),
    ]
