# Generated by Django 3.2 on 2023-09-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shopping_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionsforrecipe',
            options={'verbose_name': 'Избранный', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='shopping_list',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.AlterField(
            model_name='actionsforrecipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
