# Generated by Django 3.2.21 on 2023-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230910_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название рецепта'),
        ),
    ]
