# Generated by Django 3.2 on 2023-10-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_follow_unique_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
