# Generated by Django 3.2 on 2023-09-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230926_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionsforrecipe',
            name='name',
        ),
        migrations.AlterField(
            model_name='actionsforrecipe',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
