# Generated by Django 3.2.21 on 2023-09-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Название рецепта'),
            preserve_default=False,
        ),
    ]
