# Generated by Django 3.2 on 2023-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_shopping_list_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Добавьте фото готового блюда', upload_to='recipe_img', verbose_name='Фото блюда'),
        ),
    ]
