# Generated by Django 3.2.21 on 2023-09-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230823_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sl_Ingredient',
        ),
    ]
