# Generated by Django 3.2.22 on 2023-10-06 05:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_follow_unique_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Выберите единицу измерения', max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Выберите цвет, нажмите на цветной квадрат', image_field=None, max_length=18, samples=(('#FFFFFF', 'white'), ('#000000', 'black')), verbose_name='Цвет'),
        ),
    ]
