# Generated by Django 3.2 on 2023-10-06 05:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231006_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Выберите цвет, нажмите на цветной квадрат', image_field=None, max_length=25, samples=(('#FFFFFF', 'white'), ('#000000', 'black')), verbose_name='Цвет'),
        ),
    ]
