# Generated by Django 3.2 on 2023-10-08 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, db_table='recipes_favorited', related_name='favorited', to=settings.AUTH_USER_MODEL, verbose_name='Добавлен в избранное'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_shopping_cart',
            field=models.ManyToManyField(blank=True, db_table='recipes_shopping_cart', related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Добавлен в корзину'),
        ),
    ]
