# Generated by Django 3.2 on 2023-10-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20231008_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='in_shopping_cart',
        ),
    ]
