# Generated by Django 3.2.21 on 2023-09-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_rename_is_subscriptions_user_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscriptions',
        ),
    ]
