# Generated by Django 3.2 on 2023-10-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20231011_1724'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_ingredientrecipe',
        ),
    ]
