# Generated by Django 3.2 on 2023-10-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipeingredient_unique_ingredientrecipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredients',
        ),
    ]
